# Generated by Django 5.0.7 on 2026-05-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSERPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('competitor_url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('rank', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Competitor SERP result',
                'verbose_name_plural': 'Competitor SERP results',
                'ordering': ['-timestamp', 'rank'],
                'indexes': [models.Index(fields=['keyword'], name='seo_intel_c_keyword_9c9c8c_idx'), models.Index(fields=['-timestamp'], name='seo_intel_c_timesta_891b8f_idx'), models.Index(fields=['rank'], name='seo_intel_c_rank_929afa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentGapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('search_volume', models.IntegerField(default=0)),
                ('competitor_presence', models.BooleanField(default=False)),
                ('lcpsych_presence', models.BooleanField(default=False)),
                ('recommended_action', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Content gap record',
                'verbose_name_plural': 'Content gap records',
                'ordering': ['-timestamp', '-search_volume'],
                'indexes': [models.Index(fields=['keyword'], name='seo_intel_c_keyword_b8b278_idx'), models.Index(fields=['-search_volume'], name='seo_intel_c_search__ae1aa2_idx'), models.Index(fields=['-timestamp'], name='seo_intel_c_timesta_37c234_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeadURLHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('referrer', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Dead URL hit',
                'verbose_name_plural': 'Dead URL hits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['url'], name='seo_intel_d_url_18cd7a_idx'), models.Index(fields=['-timestamp'], name='seo_intel_d_timesta_d1a2fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternalSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Internal search query',
                'verbose_name_plural': 'Internal search queries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='seo_intel_i_timesta_2dd0d5_idx'), models.Index(fields=['term'], name='seo_intel_i_term_c66982_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('page', models.URLField(max_length=2000)),
                ('date', models.DateField()),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Search Console query',
                'verbose_name_plural': 'Search Console queries',
                'ordering': ['-date', '-clicks'],
                'indexes': [models.Index(fields=['date'], name='seo_intel_s_date_e2cc24_idx'), models.Index(fields=['query'], name='seo_intel_s_query_91b118_idx'), models.Index(fields=['page'], name='seo_intel_s_page_924deb_idx'), models.Index(fields=['-clicks'], name='seo_intel_s_clicks_710090_idx')],
                'unique_together': {('query', 'page', 'date')},
            },
        ),
    ]
