# Generated by Django 5.0.7 on 2026-05-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_intel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgaprecord',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Mark when the recommended action has been taken.'),
        ),
    ]
