# Generated by Django 5.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_intel', '0002_add_resolved_to_contentgaprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgaprecord',
            name='ignored',
            field=models.BooleanField(default=False, help_text='Dismiss this gap as not relevant.'),
        ),
    ]
