# Generated by Django 5.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_intel', '0003_contentgaprecord_ignored'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerpRawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('payload', models.JSONField(help_text='Full SerpApi response JSON for this keyword.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SERP raw result',
                'verbose_name_plural': 'SERP raw results',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['keyword'], name='seo_intel_s_keyword_serp_idx'),
                    models.Index(fields=['-timestamp'], name='seo_intel_s_timesta_serp_idx'),
                ],
            },
        ),
    ]
