# Generated by Django 5.0.7 on 2026-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_intel', '0008_keywordscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorCrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('crawled_at', models.DateTimeField()),
                ('page_count', models.IntegerField(default=0)),
                ('pages', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Competitor crawl',
                'verbose_name_plural': 'Competitor crawls',
                'ordering': ['domain'],
            },
        ),
        migrations.RenameIndex(
            model_name='competitorhit',
            new_name='seo_intel_c_keyword_b16ede_idx',
            old_name='seo_intel_c_keyword_idx',
        ),
        migrations.RenameIndex(
            model_name='competitorhit',
            new_name='seo_intel_c_competi_c6aa1d_idx',
            old_name='seo_intel_c_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='competitorhit',
            new_name='seo_intel_c_timesta_c5cfb5_idx',
            old_name='seo_intel_c_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordscore',
            new_name='seo_intel_k_priorit_53c502_idx',
            old_name='seo_intel_ks2_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordscore',
            new_name='seo_intel_k_keyword_5f521a_idx',
            old_name='seo_intel_ks2_keyword_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordsuggestion',
            new_name='seo_intel_k_source__9abde1_idx',
            old_name='seo_intel_ks_type_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordsuggestion',
            new_name='seo_intel_k_used_as_39bb84_idx',
            old_name='seo_intel_ks_seed_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordsuggestion',
            new_name='seo_intel_k_timesta_1e134d_idx',
            old_name='seo_intel_ks_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='lcpsychhit',
            new_name='seo_intel_l_keyword_5eef27_idx',
            old_name='seo_intel_lc_keyword_idx',
        ),
        migrations.RenameIndex(
            model_name='lcpsychhit',
            new_name='seo_intel_l_timesta_bde129_idx',
            old_name='seo_intel_lc_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='lcpsychhit',
            new_name='seo_intel_l_rank_6a53b9_idx',
            old_name='seo_intel_lc_rank_idx',
        ),
        migrations.RenameIndex(
            model_name='serprawresult',
            new_name='seo_intel_s_keyword_c10b16_idx',
            old_name='seo_intel_s_keyword_serp_idx',
        ),
        migrations.RenameIndex(
            model_name='serprawresult',
            new_name='seo_intel_s_timesta_594802_idx',
            old_name='seo_intel_s_timesta_serp_idx',
        ),
    ]
