# Generated by Django 5.0.7 on 2026-05-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_intel', '0009_competitorcrawl'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_domain', models.CharField(db_index=True, max_length=253)),
                ('platform', models.CharField(choices=[('gbp', 'Google Business Profile'), ('psychology_today', 'Psychology Today'), ('therapyden', 'TherapyDen'), ('zocdoc', 'ZocDoc'), ('alma', 'Alma')], db_index=True, max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('crawled_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Directory profile',
                'verbose_name_plural': 'Directory profiles',
                'ordering': ['competitor_domain', 'platform'],
                'unique_together': {('competitor_domain', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_domain', models.CharField(db_index=True, max_length=253)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], db_index=True, max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('crawled_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social profile',
                'verbose_name_plural': 'Social profiles',
                'ordering': ['competitor_domain', 'platform'],
                'unique_together': {('competitor_domain', 'platform')},
            },
        ),
    ]
