# Generated by Django 5.0.7 on 2025-11-08 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_clientfocus_remove_additionalcredential_therapist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
