# Generated by Django 5.0.7 on 2025-11-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_service_excerpt_alter_service_image_url_and_more'),
        ('profiles', '0006_therapistprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Select the services this therapist provides.', related_name='therapists', to='core.service'),
        ),
    ]
