# Generated by Django 5.0.7 on 2026-02-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_therapistprofile_home_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapistprofile',
            options={'ordering': ['home_order', 'last_name', 'first_name', 'pk']},
        ),
    ]
