# Generated by Django 5.0.7 on 2026-02-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_therapistprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone (e.g., America/New_York). Leave blank to use site default.', max_length=64),
        ),
    ]
