# Generated by Django 5.0.7 on 2026-05-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_geolocation_offers_in_office_and_more'),
        ('profiles', '0012_therapistprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Office locations where this therapist sees clients.', related_name='therapists', to='geo.geolocation'),
        ),
    ]
