# Generated by Django 5.0.7 on 2025-09-21 04:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_service_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="background_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a background image for the card and detail hero.",
                null=True,
                upload_to="services/backgrounds/",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="body",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Full detail page content (supports rich text)."
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="cta_label",
            field=models.CharField(
                blank=True, default="Learn More...", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="hero_heading",
            field=models.CharField(
                blank=True,
                help_text="Overrides the hero heading on the detail page.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="hero_subheading",
            field=models.TextField(
                blank=True,
                help_text="Intro copy that appears under the hero heading on the detail page.",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional legacy page to pull content from when no body content is provided.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_cards",
                to="core.page",
            ),
        ),
    ]
