# Generated by Django 5.0.7 on 2025-11-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short blurb shown on the homepage card and detail hero.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external/background image URL used when no file is uploaded.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display ordering on the homepage.'),
        ),
    ]
