# Generated by Django 5.0.7 on 2026-01-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_service_excerpt_alter_service_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFeeRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('professional', 'Professional Service'), ('misc', 'Miscellaneous')], default='professional', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display ordering within the category.')),
                ('doctoral_fee', models.CharField(blank=True, help_text='Shown under Doctoral level column.', max_length=100)),
                ('masters_fee', models.CharField(blank=True, help_text="Shown under Master's level column.", max_length=100)),
                ('supervised_fee', models.CharField(blank=True, help_text='Shown under Clinicians under supervision column.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Optional notes shown beneath the table when applicable.')),
            ],
            options={
                'verbose_name': 'Payment fee row',
                'verbose_name_plural': 'Payment fee rows',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
