# Generated by Django 5.0.7 on 2026-01-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_paymentfeerow"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0, help_text="Controls display order.")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
                "verbose_name": "FAQ item",
                "verbose_name_plural": "FAQ items",
            },
        ),
    ]
