# Generated by Django 5.0.7 on 2026-01-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ourphilosophy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField(help_text='Quote content shown inside the blockquote.')),
                ('author', models.CharField(blank=True, default='L+C Psychological Services', help_text='Optional author/attribution displayed below the quote.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company quote',
                'verbose_name_plural': 'Company quotes',
            },
        ),
        migrations.CreateModel(
            name='InspirationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField(help_text='Quote content shown inside the blockquote.')),
                ('author', models.CharField(blank=True, help_text='Optional author/attribution displayed below the quote.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Inspirational quote',
                'verbose_name_plural': 'Inspirational quotes',
            },
        ),
    ]
