# Generated by ChatGPT (GPT-5.1-Codex-Max) on 2026-01-14

from django.db import migrations, models


def seed_static_seo(apps, schema_editor):
    StaticPageSEO = apps.get_model('core', 'StaticPageSEO')
    defaults = [
        (
            'our-team',
            'Our Team',
            'Our Team | L+C Psychological Services',
            'Meet the licensed psychologists and therapists at L+C Psychological Services serving Northern Kentucky and Kentucky telehealth clients.',
            '',
        ),
        (
            'about-us',
            'About Us',
            'About L+C Psychological Services',
            'Learn how L+C Psychological Services supports clients with compassionate therapy, psychological testing, and a mission built on genuine connection.',
            '',
        ),
        (
            'insurance',
            'Insurance & Payment',
            'Insurance & Payment Options | L+C Psych',
            'Review accepted insurance plans, Medicare coverage, and payment details for therapy and psychological services at L+C Psychological Services.',
            '',
        ),
        (
            'contact-us',
            'Contact Us',
            'Contact L+C Psychological Services',
            'Get directions to our Florence, Kentucky office, review hours, and contact L+C Psychological Services by phone, fax, or email.',
            '',
        ),
        (
            'faq',
            'Frequently Asked Questions',
            'Therapy FAQs | L+C Psych',
            'Find answers to common questions about therapy costs, insurance coverage, first appointments, and what to expect at L+C Psychological Services.',
            '',
        ),
    ]
    for slug, page_name, title, description, keywords in defaults:
        StaticPageSEO.objects.get_or_create(
            slug=slug,
            defaults={
                'page_name': page_name,
                'seo_title': title,
                'seo_description': description,
                'seo_keywords': keywords,
            },
        )


def noop_reverse(apps, schema_editor):
    # Leave created data intact on reverse migrations
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Slug matching the URL path without leading slash, e.g., 'about-us'.", max_length=255, unique=True)),
                ('page_name', models.CharField(help_text='Friendly name shown in the admin and templates.', max_length=255)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides the <title> tag if set.', max_length=255)),
                ('seo_description', models.CharField(blank=True, help_text='Overrides the meta description if set.', max_length=300)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (optional).', max_length=500)),
                ('seo_image_url', models.URLField(blank=True, help_text='Absolute or /static URL for social sharing (og:image).')),
            ],
            options={
                'verbose_name': 'Static page SEO',
                'verbose_name_plural': 'Static page SEO entries',
                'ordering': ['page_name', 'slug'],
            },
        ),
        migrations.RunPython(seed_static_seo, noop_reverse),
    ]
