# Generated by ChatGPT (GPT-5.1-Codex-Max) on 2026-01-14

from django.db import migrations


def add_services_seo(apps, schema_editor):
    StaticPageSEO = apps.get_model('core', 'StaticPageSEO')
    StaticPageSEO.objects.get_or_create(
        slug='services',
        defaults={
            'page_name': 'Services',
            'seo_title': 'Services | L+C Psychological Services',
            'seo_description': 'Explore therapy and assessment services available through L+C Psychological Services.',
            'seo_keywords': '',
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_staticpageseo'),
    ]

    operations = [
        migrations.RunPython(add_services_seo, noop_reverse),
    ]
