# Generated by ChatGPT (GPT-5.1-Codex-Max) on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_services_staticseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpageseo',
            name='seo_image_file',
            field=models.ImageField(blank=True, help_text='Upload a social sharing image (og:image). Overrides the URL if provided.', null=True, upload_to='seo/'),
        ),
    ]
