# Generated by ChatGPT on 2026-02-20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_joinourteamsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X (Twitter)'), ('facebook_page', 'Facebook Page'), ('google_business', 'Google Business Profile'), ('linkedin_page', 'LinkedIn Page')], max_length=32, unique=True)),
                ('account_name', models.CharField(blank=True, help_text='Friendly label for the connected page/profile.', max_length=255)),
                ('account_id', models.CharField(blank=True, help_text='Platform-specific page/profile/business identifier.', max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_post_on_publish', models.BooleanField(default=True)),
                ('message_template', models.TextField(default='{title} — {excerpt} {url}', help_text="Use placeholders: {title}, {excerpt}, {url}. We'll trim to platform limits.")),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
    ]
