# Generated by ChatGPT on 2026-02-20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_socialprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('click', 'Click'), ('scroll', 'Scroll depth'), ('form_submit', 'Form submit'), ('form_error', 'Form error')], max_length=32)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Client-reported duration for the event, if applicable.')),
                ('scroll_percent', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'created'], name='core_analy_event_t_b2f14b_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['path', 'created'], name='core_analy_path_id_a78de6_idx'),
        ),
    ]
