# Generated by ChatGPT on 2026-02-20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
