# Generated by Django 5.0.7 on 2026-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_analyticsevent_location'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='core_analyt_event_t_08e568_idx',
            old_name='core_analy_event_t_b2f14b_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='core_analyt_path_063963_idx',
            old_name='core_analy_path_id_a78de6_idx',
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page view'), ('click', 'Click'), ('scroll', 'Scroll depth'), ('form_submit', 'Form submit'), ('form_error', 'Form error'), ('auth_success', 'Auth success'), ('auth_failed', 'Auth failed')], max_length=32),
        ),
    ]
