# Generated by Django 5.0.7 on 2026-02-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_core_analy_event_t_b2f14b_idx_core_analyt_event_t_08e568_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page view'), ('click', 'Click'), ('scroll', 'Scroll depth'), ('form_submit', 'Form submit'), ('form_error', 'Form error'), ('auth_success', 'Auth success'), ('auth_failed', 'Auth failed'), ('rage_click', 'Rage click'), ('dead_click', 'Dead click'), ('hover_intent', 'Hover intent'), ('session_exit', 'Session exit')], max_length=32),
        ),
    ]
