# Generated by Django 5.0.7 on 2026-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_officelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Mark as True for virtual/telehealth locations (no physical address).'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page view'), ('click', 'Click'), ('heartbeat', 'Heartbeat'), ('scroll', 'Scroll depth'), ('form_submit', 'Form submit'), ('form_error', 'Form error'), ('auth_success', 'Auth success'), ('auth_failed', 'Auth failed'), ('rage_click', 'Rage click'), ('dead_click', 'Dead click'), ('hover_intent', 'Hover intent'), ('session_exit', 'Session exit')], max_length=32),
        ),
    ]
