# Generated by Django 5.0.7 on 2026-05-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_seed_telehealth_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('heading', models.CharField(help_text='Section heading', max_length=200)),
                ('body', models.TextField(help_text='Paragraph text for this section')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
