# Generated by Django 5.0.7 on 2026-05-08 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_servicecontentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='L+C Psychological Services', help_text='Main hero heading displayed over the image.', max_length=200)),
                ('subheading', models.CharField(default='Sometimes We Get Disconnected', help_text='Subheading displayed beneath the main heading.', max_length=300)),
                ('featured_image', models.ImageField(blank=True, help_text='Background image for the hero section.', null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Hero settings',
                'verbose_name_plural': 'Hero settings',
            },
        ),
        migrations.CreateModel(
            name='HeroContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('heading', models.CharField(help_text='Block heading', max_length=200)),
                ('body', models.TextField(help_text='Paragraph text for this block')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.herosettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
