# Generated by Django 5.0.7 on 2026-05-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_herosettings_herocontentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='about_hero_image',
            field=models.ImageField(blank=True, help_text='Featured image displayed in the About Us page hero section.', null=True, upload_to='hero/'),
        ),
    ]
