# Generated by Django 5.0.7 on 2026-05-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_about_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='about_heading',
            field=models.CharField(default='About L+C Psychological Services', help_text='Main H1 heading in the About Us page hero.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='about_subheading',
            field=models.CharField(default='Founded on the belief that genuine connection is the foundation of healing — we are a team of dedicated psychologists and therapists serving Northern Kentucky and beyond.', help_text='Subheading paragraph in the About Us page hero.', max_length=400),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='clinicians_heading',
            field=models.CharField(default='Meet Our Clinicians', help_text='Heading for the Meet Our Clinicians section on the About Us page.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='clinicians_subtext',
            field=models.CharField(default='Our team of licensed psychologists and therapists brings expertise, warmth, and dedication to every client they serve.', help_text='Subtitle beneath the clinicians heading.', max_length=400),
        ),
        migrations.AddField(
            model_name='ourphilosophy',
            name='value1_description',
            field=models.TextField(default='We believe meaningful relationships are central to healing and growth — both within therapy and in every area of life.', help_text='First value card description.'),
        ),
        migrations.AddField(
            model_name='ourphilosophy',
            name='value1_title',
            field=models.CharField(default='Connection', help_text='First value card title.', max_length=100),
        ),
        migrations.AddField(
            model_name='ourphilosophy',
            name='value2_description',
            field=models.TextField(default='We meet every client with empathy, warmth, and genuine care — creating a safe space where you feel heard and understood.', help_text='Second value card description.'),
        ),
        migrations.AddField(
            model_name='ourphilosophy',
            name='value2_title',
            field=models.CharField(default='Compassion', help_text='Second value card title.', max_length=100),
        ),
        migrations.AddField(
            model_name='ourphilosophy',
            name='value3_description',
            field=models.TextField(default='We help clients build the skills, insight, and resilience needed to thrive — supporting real, lasting change at every stage of life.', help_text='Third value card description.'),
        ),
        migrations.AddField(
            model_name='ourphilosophy',
            name='value3_title',
            field=models.CharField(default='Growth', help_text='Third value card title.', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='cta_label',
            field=models.CharField(blank=True, default='Schedule Your First Appointment', max_length=200),
        ),
    ]
