# Generated by Django 5.0.7 on 2026-05-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_socialprofile_client_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gone410URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
