# Generated by Django 5.0.7 on 2026-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_modality_condition_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Decimal latitude, e.g. 39.008625', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Decimal longitude, e.g. -84.647614', max_digits=9, null=True),
        ),
    ]
