# Generated by ChatGPT on 2026-02-15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
