# Generated by Django 5.0.7 on 2026-05-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'kentucky'", unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Kentucky'", max_length=100)),
                ('abbreviation', models.CharField(help_text="Two-letter postal code, e.g. 'KY'", max_length=2)),
                ('seo_title', models.CharField(blank=True, help_text='Full <title> tag value. Leave blank for auto-generated default.', max_length=200)),
                ('seo_description', models.CharField(blank=True, help_text='Meta description (aim for ≤160 chars). Leave blank for auto-generated default.', max_length=300)),
                ('hero_heading', models.CharField(blank=True, help_text='H1 text displayed on the page. Leave blank to use the state name.', max_length=200)),
                ('hero_subheading', models.TextField(blank=True, help_text='Intro paragraph beneath the H1.')),
                ('og_image_url', models.URLField(blank=True, help_text='Absolute URL to the Open Graph / social share image.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this state from the site without deleting it.')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'florence' or 'boone-county'")),
                ('name', models.CharField(help_text="Display name, e.g. 'Florence' or 'Boone County'", max_length=100)),
                ('location_type', models.CharField(choices=[('city', 'City'), ('county', 'County')], help_text='Whether this entry is a city or a county.', max_length=10)),
                ('seo_title', models.CharField(blank=True, help_text='Full <title> tag value. Leave blank for auto-generated default.', max_length=200)),
                ('seo_description', models.CharField(blank=True, help_text='Meta description (aim for ≤160 chars). Leave blank for auto-generated default.', max_length=300)),
                ('hero_heading', models.CharField(blank=True, help_text='H1 text displayed on the page. Leave blank for auto-generated default.', max_length=200)),
                ('hero_subheading', models.TextField(blank=True, help_text='Intro paragraph beneath the H1.')),
                ('og_image_url', models.URLField(blank=True, help_text='Absolute URL to the Open Graph / social share image.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this location from the site without deleting it.')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='geo.geostate')),
            ],
            options={
                'verbose_name': 'Location (City / County)',
                'verbose_name_plural': 'Locations (Cities / Counties)',
                'ordering': ['name'],
                'unique_together': {('state', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GeoContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('heading', models.CharField(help_text='H2 section heading', max_length=200)),
                ('body', models.TextField(help_text='Paragraph text for this section')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='geo.geolocation')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='geo.geostate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
