# Generated by Django 5.0.7 on 2026-05-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='county',
            field=models.ForeignKey(blank=True, help_text='The county this city belongs to (cities only).', limit_choices_to={'location_type': 'county'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='geo.geolocation'),
        ),
    ]
