# Generated by Django 5.0.7 on 2026-05-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_geolocation_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Hero background image displayed on this location's page.", null=True, upload_to='geo/locations/'),
        ),
        migrations.AddField(
            model_name='geostate',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero background image displayed on the state landing page.', null=True, upload_to='geo/states/'),
        ),
    ]
