# Generated by Django 5.0.7 on 2026-05-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_geolocation_hero_image_geostate_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='offers_in_office',
            field=models.BooleanField(default=True, help_text='In-office appointments are available in this location.'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='offers_telehealth',
            field=models.BooleanField(default=True, help_text='Telehealth appointments are available in this location.'),
        ),
        migrations.AddField(
            model_name='geostate',
            name='offers_in_office',
            field=models.BooleanField(default=True, help_text='In-office appointments are available in this state.'),
        ),
        migrations.AddField(
            model_name='geostate',
            name='offers_telehealth',
            field=models.BooleanField(default=True, help_text='Telehealth appointments are available in this state.'),
        ),
    ]
