# Generated by Django 5.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_geolocation_offers_in_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, help_text="URL-safe identifier, e.g. 'greater-cincinnati'")),
                ('name', models.CharField(max_length=100, help_text="Display name, e.g. 'Greater Cincinnati Area'")),
                ('seo_title', models.CharField(max_length=200, blank=True, help_text='Full <title> tag value. Leave blank for auto-generated default.')),
                ('seo_description', models.CharField(max_length=300, blank=True, help_text='Meta description (aim for \u2264160 chars). Leave blank for auto-generated default.')),
                ('og_image_url', models.URLField(max_length=500, blank=True, help_text='Absolute URL to the Open Graph / social share image.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='geo/regions/', help_text="Hero background image displayed on this region's page.")),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this region from the site without deleting it.')),
                ('states', models.ManyToManyField(blank=True, help_text='States that are part of this region.', related_name='regions', to='geo.geostate')),
                ('locations', models.ManyToManyField(blank=True, help_text='Cities and counties that are part of this region.', related_name='regions', to='geo.geolocation')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
    ]
